# Generated by Django 4.2.6 on 2023-10-08 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProposeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50, verbose_name="ФИО")),
                ("email", models.EmailField(max_length=50, verbose_name="Почта")),
                (
                    "suggestion",
                    models.TextField(max_length=200, verbose_name="Предложения"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            10,
                            8,
                            23,
                            46,
                            32,
                            552838,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение",
                "verbose_name_plural": "Предложения",
                "ordering": ["-date", "full_name"],
            },
        ),
    ]
