# Generated by Django 4.2.6 on 2023-10-09 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposemodel",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 9, 1, 6, 34, 521836, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="proposemodel",
            name="email",
            field=models.TextField(max_length=50, verbose_name="Почта"),
        ),
    ]
