# Generated by Django 4.2.6 on 2023-10-09 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf", "0002_alter_proposemodel_date_alter_proposemodel_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposemodel",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 9, 1, 24, 24, 687933, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
