# Generated by Django 4.2.6 on 2023-10-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf", "0004_alter_proposemodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposemodel",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
